
INSERT INTO team(name) VALUES ('General'),('APT'),
('Front Arena'), ('XSP'), ('Quantum'), ('Sierra'),
('Insurance'), ('Adaptiv'), ('Apex Collateral'),
('PTDS '), ('ITDS');

INSERT INTO tag(name) VALUES ('finance'), ('technical'),
('procedural'), ('product'), ('clients');

INSERT INTO users(name, surname, e_number, email, password, is_admin, team_team_id ) VALUES
('Ana', 'Stakic', 'e5637521', 'ana.stakic@fisglobal.com', 'dictionary123*', 1, 3 ),
('Aleksandra', 'Maksimovic', 'e5638600', 'aleksandra.maksimovic@fisglobal.com', 'dictionary123*', 1, 2 ),
('Nikola', 'Vitorovic', 'e5598277', 'nikola.vitorovic@fisglobal.com', 'dictionary123*', 1, 2 ),
('Nina', 'Milanovic', 'e5638799', 'nina.milanovic@fisglobal.com', 'dictionary123*', 1, 2 );

INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (1, 'Yield refers to the earnings generated and realized on an investment over a particular period of time.', ' It\'s expressed as a percentage based on the invested amount, current market value, or face value of the security. It includes the interest earned or dividends received from holding a particular security. Depending on the valuation (fixed vs. fluctuating) of the security, yields may be classified as known or anticipated.', 'Yeald', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (2, 'Quantity demanded is a term used in economics to describe the total amount of a good or service that consumers demand over a given interval of time. ', 'Quantity demanded is a term used in economics to describe the total amount of a good or service that consumers demand over a given interval of time. It depends on the price of a good or service in a marketplace, regardless of whether that market is in equilibrium.', 'Quantity Demanded', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (3, 'Leverage results from using borrowed capital as a funding source when investing to expand the firm\'s asset base and generate returns on risk capital.', ' Leverage is an investment strategy of using borrowed money—specifically, the use of various financial instruments or borrowed capital—to increase the potential return of an investment. Leverage can also refer to the amount of debt a firm uses to finance assets.', 'Leverage', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (4, 'Liquidity refers to the efficiency or ease with which an asset or security can be converted into ready cash without affecting its market price. ', 'Liquidity refers to the efficiency or ease with which an asset or security can be converted into ready cash without affecting its market price. The most liquid asset of all is cash itself.', 'Liquidity', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (5, 'A hedge is an investment that is made with the intention of reducing the risk of adverse price movements in an asset. Normally, a hedge consists of taking an offsetting or opposite position in a related security.', 'Hedging is a strategy that tries to limit risks in financial assets.', 'Hedge', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (6, 'Hedge funds are alternative investments using pooled funds that employ different strategies to earn active returns, or alpha, for their investors.', 'Hedge funds are alternative investments using pooled funds that employ different strategies to earn active returns, or alpha, for their investors. Hedge funds may be aggressively managed or make use of derivatives and leverage in both domestic and international markets with the goal of generating high returns (either in an absolute sense or over a specified market benchmark).', 'Hedge Fund', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (7, 'Gross income for an individual—also known as gross pay when it\'s on a paycheck—is the individual’s total pay from his or her employer before taxes or other deductions.', 'Gross income for an individual consists of income from wages and salary plus other forms of income, including pensions, interest, dividends and rental income.2﻿', 'Gross income', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (8, 'An exchange rate is the value of one nation\'s currency versus the currency of another nation or economic zone. ', 'An exchange rate is the value of a country\'s currency vs. that of another country or economic zone.', 'Exchange Rate', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (9, 'A derivative is a financial security with a value that is reliant upon or derived from, an underlying asset or group of assets—a benchmark.', 'The derivative itself is a contract between two or more parties, and the derivative derives its price from fluctuations in the underlying asset.', 'Derivative', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (10, 'A bond is a fixed income instrument that represents a loan made by an investor to a borrower (typically corporate or governmental). ', 'Bonds are units of corporate debt issued by companies and securitized as tradeable assets.', 'Bond', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (11, 'An asset is a resource with economic value that an individual, corporation, or country owns or controls with the expectation that it will provide a future benefit.', 'An asset is a resource with economic value that an individual, corporation, or country owns or controls with the expectation that it will provide a future benefit.', 'Asset', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (12, 'An acquisition is when one company purchases most or all of another company\'s shares to gain control of that company. ', 'An acquisition occurs when one company buys most or all of another company\'s shares.', 'Acquisition', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (13, 'Warrants are a derivative that give the right, but not the obligation, to buy or sell a security—most commonly an equity—at a certain price before expiration. ', ' The price at which the underlying security can be bought or sold is referred to as the exercise price or strike price. An American warrant can be exercised at any time on or before the expiration date, while European warrants can only be exercised on the expiration date. Warrants that give the right to buy a security are known as call warrants; those that give the right to sell a security are known as put warrants. ', 'Warrant', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (14, 'Vesting is a legal term that means to give or earn a right to a present or future payment, asset, or benefit.', 'In the context of retirement plan benefits, vesting gives employees rights to employer-provided assets over time, which gives the employees an incentive to perform well and remain with a company. The vesting schedule set up by a company determines when employees acquire full ownership of the asset.', 'Vesting', 1);
INSERT INTO `dictionary`.`term` (`term_id`, `description`, `details`, `title`, `team_team_id`) VALUES (15, 'A trust fund is an estate planning tool that establishes a legal entity to hold property or assets for a person or organization.', 'A trust fund is designed to hold and manages assets on someone else\'s behalf, with the help of a neutral third-party.', 'Trust fund', '1');
